[package]
name = "carbonado"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "An apocalypse-resistant data storage format for the truly paranoid."
documentation = "https://docs.rs/carbonado"
homepage = "https://github.com/diba-io/carbonado"
repository = "https://github.com/diba-io/carbonado.git"

[dependencies]
anyhow = "1"
bao = "0.12.1"
ecies = { version = "0.2.2", default-features = false, features = ["pure"] }
serde = "1"
snap = "1"
zfec-rs = "0.1.0"

[dev-dependencies]
wasm-bindgen-test = "0.3"
